package ui;

import system.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import entities.GamePanel;

public class MainGameFrame extends JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MainGameFrame.class.getName());
    private ImageBackground imageBg;
    private JButton buttonStart, buttonSetting, buttonExit;
    private JLabel titleGame, picture;
    private JPanel leftPanel, groupButtonPanel;
    private ImageIcon logoIcon, startNormalIcon, settingNormalIcon, exitNormalIcon, startHoverIcon, settingHoverIcon, exitHoverIcon;
    private MenuActionHandler action;
    private SettingPanel settingPanel;
    private JLayeredPane layeredPane;
    private Dimension screenSize;
    private int widthSystem, heightSystem, settingW, settingH;
    private CardLayout cardLayout;
    private JPanel mainCardPanel;
    private CutscenePanel cutscenePanel;
    private GamePanel gamePanel;
    private FadeTransition fadeTransition;
    private GameOverPanel gameOverPanel;
    private Tutorial tutorial;

    public MainGameFrame() {
        this.setUndecorated(true);
        layeredPane = new JLayeredPane();
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        widthSystem = (int) screenSize.getWidth();
        heightSystem = (int) screenSize.getHeight();
        settingPanel = new SettingPanel(this);
        settingPanel.setVisible(false);

        gameOverPanel = new GameOverPanel(this);
        gameOverPanel.setVisible(false);
        gameOverPanel.setBounds(0, 0, widthSystem, heightSystem);

        fadeTransition = new FadeTransition();
        fadeTransition.setBounds(0,0, widthSystem, heightSystem);
        initMenuPanel();

        gamePanel = new GamePanel(this, fadeTransition);
        cutscenePanel = new CutscenePanel();
        cardLayout = new CardLayout();
        mainCardPanel = new JPanel(cardLayout);
        mainCardPanel.setBounds(0, 0, widthSystem, heightSystem);

        tutorial = new Tutorial(this);
        tutorial.setBounds(0, 0, widthSystem, heightSystem);

        mainCardPanel.add(imageBg, "MENU");
        mainCardPanel.add(cutscenePanel, "CUTSCENE");
        mainCardPanel.add(gamePanel, "GAME");

        settingPanel.setBounds(0, 0, widthSystem, heightSystem);

        layeredPane.add(mainCardPanel, JLayeredPane.DEFAULT_LAYER);      // ชั้นหลังสุด
        layeredPane.add(settingPanel, JLayeredPane.PALETTE_LAYER);      // ชั้นเมนู Setting (ต้องอยู่เหนือเมนูหลัก)
        layeredPane.add(gameOverPanel, JLayeredPane.MODAL_LAYER);
        layeredPane.add(tutorial, JLayeredPane.POPUP_LAYER);
        layeredPane.add(fadeTransition, JLayeredPane.DRAG_LAYER);       // ชั้นหน้าสุดสำหรับฉาก Fade

        cardLayout.show(mainCardPanel, "MENU");
        this.setContentPane(layeredPane);
        this.revalidate();
        this.repaint();

        AudioManager.playMusic("src/res/sound/MenuBackgroundMusic.wav", 0.0f);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        try {
            this.setIconImage(logoIcon.getImage());
        } catch (Exception e) {
            System.err.println("ระบบ: ไม่สามารถเปลี่ยนไอคอนโปรแกรมได้");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")

    private void initMenuPanel() {
        imageBg = new ImageBackground("src/res/MenuBackground.png");
        leftPanel = new JPanel();
        groupButtonPanel = new JPanel();
        startNormalIcon = new ImageIcon(new ImageIcon("src/res/MenuStartNormalBtn.png").getImage().getScaledInstance(351, 84, Image.SCALE_SMOOTH));
        settingNormalIcon = new ImageIcon(new ImageIcon("src/res/MenuSettingNormalBtn.png").getImage().getScaledInstance(294, 84, Image.SCALE_SMOOTH));
        exitNormalIcon = new ImageIcon(new ImageIcon("src/res/MenuExitNormalBtn.png").getImage().getScaledInstance(483, 38, Image.SCALE_SMOOTH));
        startHoverIcon = new ImageIcon(new ImageIcon("src/res/MenuStartHoverBtn.png").getImage().getScaledInstance(351, 84, Image.SCALE_SMOOTH));
        settingHoverIcon = new ImageIcon(new ImageIcon("src/res/MenuSettingHoverBtn.png").getImage().getScaledInstance(294, 84, Image.SCALE_SMOOTH));
        exitHoverIcon = new ImageIcon(new ImageIcon("src/res/MenuExitHoverBtn.png").getImage().getScaledInstance(483, 38, Image.SCALE_SMOOTH));
        buttonStart = new JButton(startNormalIcon);
        buttonSetting = new JButton(settingNormalIcon);
        buttonExit = new JButton(exitNormalIcon);
        buttonStart.setRolloverIcon(startHoverIcon);
        buttonSetting.setRolloverIcon(settingHoverIcon);
        buttonExit.setRolloverIcon(exitHoverIcon);

        leftPanel.setLayout(new BoxLayout(leftPanel, BoxLayout.Y_AXIS));
        leftPanel.setOpaque(false);
        leftPanel.setBorder(new EmptyBorder(50, 0, 0, 0));

        imageBg.setLayout(new BorderLayout());
        imageBg.setBorder(new EmptyBorder(50, 80, 50, 0));

        // Title Game Name
        titleGame = new JLabel();
        logoIcon = new ImageIcon(new ImageIcon("src/res/MenuLogo.png").getImage().getScaledInstance(600, 350, Image.SCALE_SMOOTH));
        titleGame.setIcon(logoIcon);
        titleGame.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Content button
        groupButtonPanel.setLayout(new BoxLayout(groupButtonPanel, BoxLayout.Y_AXIS));
        groupButtonPanel.setOpaque(false);
        groupButtonPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        groupButtonPanel.setAlignmentX(0.5f);

        setupButtonCenter(buttonStart);
        setupButtonCenter(buttonSetting);
        setupButtonCenter(buttonExit);

        groupButtonPanel.add(buttonStart);
        groupButtonPanel.add(Box.createRigidArea(new Dimension(0, 40)));
        groupButtonPanel.add(buttonSetting);
        groupButtonPanel.add(Box.createRigidArea(new Dimension(0, 70)));
        groupButtonPanel.add(buttonExit);

        leftPanel.add(titleGame);
        leftPanel.add(Box.createRigidArea(new Dimension(0, 110)));
        leftPanel.add(groupButtonPanel);

        imageBg.setLayout(new BorderLayout());
        imageBg.add(leftPanel, BorderLayout.WEST);

        action = new MenuActionHandler(this);
        buttonStart.setActionCommand("Start");
        buttonSetting.setActionCommand("Setting");
        buttonExit.setActionCommand("Exit");
        buttonStart.addActionListener(action);
        buttonSetting.addActionListener(action);
        buttonExit.addActionListener(action);
        buttonStart.addMouseListener(action);
        buttonSetting.addMouseListener(action);
        buttonExit.addMouseListener(action);

        setTitle("Phawang");
    }

    private void customizeButton(JButton btn) {
        btn.setContentAreaFilled(false); // ลบพื้นหลังปุ่ม
        btn.setBorderPainted(false);     // ลบขอบปุ่ม
        btn.setFocusPainted(false);      // ลบเส้นประเวลาคลิก
        btn.setOpaque(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR)); // เปลี่ยนเมาส์เป็นรูปมือ
        btn.setAlignmentX(Component.LEFT_ALIGNMENT);
    }

    private void setupButtonCenter(JButton btn) {
        customizeButton(btn); // เรียกใช้ฟังก์ชันทำให้ปุ่มใสที่คุณมีอยู่แล้ว
        btn.setAlignmentX(Component.LEFT_ALIGNMENT); // บังคับปุ่มเกาะเส้นกึ่งกลาง
    }

    public void toggleSetting(boolean show, boolean isInGame) {
        if (show) {
            // ก่อนจะโชว์ ให้สั่งตั้งค่าโหมดปุ่มก่อน
            settingPanel.setInGameMode(isInGame);
        }
        if (!show) {
            gamePanel.requestFocusInWindow();
        }

        settingPanel.setVisible(show);
        layeredPane.revalidate();
        layeredPane.repaint();
    }
    // 1. เมื่อกดปุ่ม Setting จาก "หน้าเมนู"
    public void openSettingFromMenu() {
        // ส่ง false เข้าไปเพื่อบอกว่าไม่ได้อยู่ภายในเกม (จะโชว์แค่ปุ่ม Back)
        toggleSetting(true, false);
    }

    // 2. เมื่อกดปุ่ม Esc จาก "ภายในเกม"
    public void openSettingFromGame() {
        // ส่ง true เข้าไปเพื่อบอกว่าอยู่ภายในเกม (จะโชว์ Back + Return คู่กัน)
        toggleSetting(true, true);
    }

    // 3. อย่าลืมสร้างเมธอดกลางสำหรับกลับหน้าเมนูด้วยจ้ะ
    public void returnToMainMenu() {
        // 1. หยุดการทำงานของ GamePanel
        gamePanel.stopGameThread();

        // 2. สลับ CardLayout กลับไปที่หน้า MENU
        cardLayout.show(mainCardPanel, "MENU");

        // 3. เปลี่ยนเพลงประกอบกลับเป็นเพลงหน้าเมนู
        AudioManager.playMusic("src/res/sound/BackgroundMusic.wav", 0.0f);

        // 4. บังคับให้หน้าเมนูรับโฟกัส (เพื่อให้กดปุ่มเริ่มเกมใหม่ได้)
        imageBg.requestFocusInWindow();
    }

    public void showGameOver(boolean show) {
        if (show) {
            gamePanel.stopGameThread(); // หยุดลูปเกม
        }
        gameOverPanel.setVisible(show);

        if (show) {
            gameOverPanel.requestFocusInWindow();
        }
        layeredPane.revalidate();
        layeredPane.repaint();
    }

    public void startCutscene() {
        String[] introStory = {
                "กริ๊งๆๆๆ น้ำตาลโทรมา",
                "รับสายโทรศัพท์น้ำตาล",
                "อึ่งๆๆๆๆๆ",
                "ไปงานศพด้วยจ้าเพื่อน"
        };

        fadeTransition.executeFade(350, 0, 350,() ->{
            cardLayout.show(mainCardPanel, "CUTSCENE"); // สลับเป็นหน้าเล่นเกม

            cutscenePanel.startCutscene(introStory, true, false, () -> {
                transitionToGame();
            }); // สั่งให้ข้อความเริ่มวิ่ง
        });

    }

    // เรียกตอนคัดซีนฉายจบแล้ว
    public void transitionToGame() {
        fadeTransition.executeFade(0, 0, 600, () -> {
            cardLayout.show(mainCardPanel, "GAME");
            gamePanel.startGameThread();
            gamePanel.requestFocusInWindow();

            tutorial.showTutorial();
        });
    }

    public void retryFromGameOver() {
        cardLayout.show(mainCardPanel, "GAME");

        if (gamePanel != null) {
            gamePanel.startGameThread();
        }

        gamePanel.sceneManager.startTransition("scene_5", gamePanel.mainPlayer, 800, 550);

        gamePanel.requestFocusInWindow();
    }

    public GamePanel getGamePanel() {
        return gamePanel;
    }

    public static void main(String args[]) {
        System.setProperty("sun.java2d.uiScale", "1.0");
        try {
            // ตั้งค่า Look And Feel ให้เหมือน OS
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGameFrame().setVisible(true));
    }
}
