package ui;

import system.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

public class MainGameFrame extends JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGameFrame.class.getName());
    private JDesktopPane desktopPane;
    private ImageBackground imageBg;
    private JButton buttonStart, buttonSetting, buttonExit;
    private JLabel titleGame, picture;
    private JPanel contentPanel, buttonPanel;
    private ImageIcon icon;
    private Image scaled;
    private MenuActionHandler action;
    private SettingPanel settingPanel;
    private JLayeredPane layeredPane;
    private Dimension screenSize;
    private int widthSystem, heightSystem, settingW, settingH;

    public MainGameFrame() {

        this.setUndecorated(true);
        layeredPane = new JLayeredPane();
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        widthSystem = (int) screenSize.getWidth();
        heightSystem = (int) screenSize.getHeight();

        initMenuPanel();
        settingPanel = new SettingPanel(this);
        settingPanel.setVisible(false);

        imageBg.setBounds(0, 0, widthSystem, heightSystem);
        layeredPane.add(imageBg, JLayeredPane.DEFAULT_LAYER);

        settingW = 1000;
        settingH = 600;
        settingPanel.setBounds((widthSystem - settingW) / 2, (heightSystem - settingH) / 2, settingW, settingH);
        layeredPane.add(settingPanel, JLayeredPane.PALETTE_LAYER);

        this.setContentPane(layeredPane);
        this.revalidate();
        this.repaint();

        AudioManager.playMusic("src/res/sound/BackgroundMusic.wav");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initMenuPanel() {
        desktopPane = new JDesktopPane();
        imageBg = new ImageBackground("src/res/Menu.png");
        contentPanel = new JPanel(new GridLayout(1, 2));
        buttonPanel = new JPanel();
        buttonStart = new JButton("Start");
        buttonSetting = new JButton("Setting");
        buttonExit = new JButton("Exit");
        picture = new JLabel();
        icon = new ImageIcon("src/res/Front Menu Right.png");


        imageBg.setLayout(new BorderLayout());
        imageBg.setLayout(new BorderLayout(50, 50));
        imageBg.setBorder(new EmptyBorder(50, 100, 0, 0));
        desktopPane.setOpaque(false);
        imageBg.add(desktopPane, BorderLayout.CENTER);

        //Title Game Name
        titleGame = new JLabel("Phawang", SwingConstants.CENTER);
        titleGame.setFont(new Font("Arial", Font.BOLD, 200));
        imageBg.add(titleGame, BorderLayout.NORTH);

        //Content button + picture
        contentPanel.setOpaque(false);

        buttonPanel.setLayout(new BoxLayout(buttonPanel, BoxLayout.Y_AXIS));   //Add Button Left Menu
        buttonPanel.setOpaque(false);
        buttonPanel.add(Box.createVerticalGlue());
        customizeButton(buttonStart);
        customizeButton(buttonSetting);
        customizeButton(buttonExit);
        buttonPanel.add(buttonStart);
        buttonPanel.add(Box.createRigidArea(new Dimension(0, 50)));
        buttonPanel.add(buttonSetting);
        buttonPanel.add(Box.createRigidArea(new Dimension(0, 50)));
        buttonPanel.add(buttonExit);
        buttonPanel.add(Box.createVerticalGlue());

        picture.setOpaque(false);     //Add Picture Right Menu
        scaled = icon.getImage().getScaledInstance(700, 1000, Image.SCALE_SMOOTH);
        picture.setHorizontalAlignment(JLabel.RIGHT);
        picture.setVerticalAlignment(JLabel.BOTTOM);
        picture.setIcon(new ImageIcon(scaled));
        picture.setText("");

        contentPanel.add(buttonPanel);
        contentPanel.add(picture);
        imageBg.add(contentPanel, BorderLayout.CENTER);

        action = new MenuActionHandler(this);
        buttonStart.addActionListener(action);
        buttonSetting.addActionListener(action);
        buttonExit.addActionListener(action);

        setTitle("Phawang");
    }

    private void customizeButton(JButton btn) {
        btn.setFont(new Font("Arial", Font.PLAIN, 150)); // ปรับขนาดฟอนต์ให้ใหญ่ขึ้น
        btn.setAlignmentX(Component.LEFT_ALIGNMENT); // ชิดซ้ายตามใน mockup
        btn.setFocusable(false); // เอาเส้นประตอนเลือกออก

//        btn.setContentAreaFilled(false);
//        btn.setBorderPainted(false);
//        btn.setOpaque(false);
    }

    public void toggleSetting(boolean show) {
        settingPanel.setVisible(show);
        buttonPanel.setVisible(!show);
        layeredPane.revalidate();
        layeredPane.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.setProperty("sun.java2d.uiScale", "1.0");
        try {
            // ตั้งค่า Look And Feel ให้เหมือน OS
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGameFrame().setVisible(true));
    }
}
