import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.*;

public class MainGameFrame extends JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGameFrame.class.getName());
    private JDesktopPane desktopPane;
    private JButton jButton1;
    private ImageBackground imageBg;
    private JButton buttonStart, buttonNewGame, buttonExit;
    private JLabel titleGame, picture;
    private JPanel contentPanel, buttonPanel;
    private ImageIcon icon;
    private Image scaled;
    private MenuActionHandler action;

    public MainGameFrame() {
        desktopPane = new JDesktopPane();
        imageBg = new ImageBackground("res/Menu.png");
        contentPanel = new JPanel(new GridLayout(1, 2));
        buttonPanel = new JPanel();
        buttonStart = new JButton("Start");
        buttonNewGame = new JButton("New Game");
        buttonExit = new JButton("Exit");
        picture = new JLabel();
        icon = new ImageIcon("res/Front Menu Right.png");

        this.setUndecorated(true);
        imageBg.setLayout(new BorderLayout());
        imageBg.setLayout(new BorderLayout(50, 50));
        imageBg.setBorder(new EmptyBorder(50, 100, 0, 0));
        desktopPane.setOpaque(false);
        imageBg.add(desktopPane, BorderLayout.CENTER);
        this.setContentPane(imageBg);

        //Title Game Name
        titleGame = new JLabel("Phawang", SwingConstants.CENTER);
        titleGame.setFont(new Font("Arial", Font.BOLD, 200));
        imageBg.add(titleGame, BorderLayout.NORTH);

        //Content button + picture
        contentPanel.setOpaque(false);

        buttonPanel.setLayout(new BoxLayout(buttonPanel, BoxLayout.Y_AXIS));   //Add Button Left Menu
        buttonPanel.setOpaque(false);
        buttonPanel.add(Box.createVerticalGlue());
        customizeButton(buttonStart);
        customizeButton(buttonNewGame);
        customizeButton(buttonExit);
        buttonPanel.add(buttonStart);
        buttonPanel.add(Box.createRigidArea(new Dimension(0, 50)));
        buttonPanel.add(buttonNewGame);
        buttonPanel.add(Box.createRigidArea(new Dimension(0, 50)));
        buttonPanel.add(buttonExit);
        buttonPanel.add(Box.createVerticalGlue());

        picture.setOpaque(false);     //Add Picture Right Menu
        scaled = icon.getImage().getScaledInstance(700, 1000, Image.SCALE_SMOOTH);
        picture.setHorizontalAlignment(JLabel.RIGHT);
        picture.setVerticalAlignment(JLabel.BOTTOM);
        picture.setIcon(new ImageIcon(scaled));
        picture.setText("");

        contentPanel.add(buttonPanel);
        contentPanel.add(picture);
        imageBg.add(contentPanel, BorderLayout.CENTER);

        action = new MenuActionHandler(this);
        buttonStart.addActionListener(action);
        buttonNewGame.addActionListener(action);
        buttonExit.addActionListener(action);

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Phawang");
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">

    private void jButton1ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
        GameWindow gameWin = new GameWindow();
        GamePanel gamePanel = new GamePanel();
        gameWin.add(gamePanel);
        gameWin.pack();
        desktopPane.add(gameWin);
        gameWin.setVisible(true);
    }

    private void customizeButton(JButton btn) {
        btn.setFont(new Font("Arial", Font.PLAIN, 150)); // ปรับขนาดฟอนต์ให้ใหญ่ขึ้น
        btn.setAlignmentX(Component.LEFT_ALIGNMENT); // ชิดซ้ายตามใน mockup
        btn.setFocusable(false); // เอาเส้นประตอนเลือกออก
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // ตั้งค่า Look And Feel ให้เหมือน OS
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGameFrame().setVisible(true));
    }
}
