import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class MainGameFrame extends JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGameFrame.class.getName());
    private JDesktopPane desktopPane;
    private JButton jButton1;
    private ImageBackground imageBg;

    /**
     * Creates new form MainGameFrame
     */
    public MainGameFrame() {
        imageBg = new ImageBackground("res/Menu.png");

        this.setUndecorated(true);
        initComponents();

        imageBg.setLayout(new BorderLayout());
        desktopPane.setOpaque(false);
        imageBg.add(desktopPane, BorderLayout.CENTER);
        this.setContentPane(imageBg);

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Phawang");
//        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().setFullScreenWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        desktopPane = new JDesktopPane();
        jButton1 = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Start Game");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        desktopPane.setLayer(jButton1, JLayeredPane.DEFAULT_LAYER);

        GroupLayout desktopPaneLayout = new GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
                desktopPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jButton1)
                                .addContainerGap(155, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
                desktopPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jButton1)
                                .addContainerGap(143, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(desktopPane, GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
        GameWindow gameWin = new GameWindow();
        GamePanel gamePanel = new GamePanel();
        gameWin.setContentPane(gamePanel);
        gameWin.pack();
        desktopPane.add(gameWin);
        gameWin.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGameFrame().setVisible(true));
    }
}
